import Foundation

/// Small localization seam shared by the app and the widget extension.
///
/// SwiftUI can discover literal `Text` values automatically, but dynamic
/// strings returned from domain models, notifications, widgets, and Live
/// Activities need an explicit lookup. `Bundle.main` resolves to the app or
/// extension bundle at runtime, so the same code works in both targets.
enum BSLocalization {
    static func text(_ key: String) -> String {
        let localized = NSLocalizedString(key, bundle: .main, comment: "")
        guard localized == key, let fallback = measurementUnitFallback(for: key) else {
            return localized
        }
        return fallback
    }

    static func format(_ key: String, _ arguments: CVarArg...) -> String {
        String(format: text(key), arguments: arguments)
    }

    /// A few compact time-unit labels are generated by the system instead of
    /// duplicating them across large app/widget string tables. This is only a
    /// fallback: an explicit localization key always wins.
    private static func measurementUnitFallback(for key: String) -> String? {
        let unit: Unit
        switch key {
        case "秒": unit = UnitDuration.seconds
        default: return nil
        }

        let formatter = MeasurementFormatter()
        formatter.locale = selectedLocale
        formatter.unitStyle = .long
        return formatter.string(from: unit)
    }

    /// AppLanguageManager persists the app override under this key. Reading it
    /// here keeps the shared localization seam independent from the app target,
    /// while still making an in-app language change affect generated unit names.
    private static var selectedLocale: Locale {
        if let identifier = UserDefaults.standard.string(forKey: "appLanguage"), !identifier.isEmpty {
            return Locale(identifier: identifier)
        }
        return .autoupdatingCurrent
    }
}
