import Foundation

/// Small localization seam shared by the app and the widget extension.
///
/// SwiftUI can discover literal `Text` values automatically, but dynamic
/// strings returned from domain models, notifications, widgets, and Live
/// Activities need an explicit lookup. `Bundle.main` resolves to the app or
/// extension bundle at runtime, so the same code works in both targets.
enum BSLocalization {
    static func text(_ key: String) -> String {
        let localized = NSLocalizedString(key, bundle: .main, comment: "")
        guard localized == key else { return localized }

        if let fallback = countdownFallback(for: key) {
            return fallback
        }
        if let fallback = measurementUnitFallback(for: key) {
            return fallback
        }
        return localized
    }

    static func format(_ key: String, _ arguments: CVarArg...) -> String {
        String(format: text(key), arguments: arguments)
    }

    /// Countdown labels used by dynamic `Text` lookups need an explicit fallback
    /// when one target's generated string table lags another target's table.
    /// Explicit resource localizations always win before this code runs.
    private static func countdownFallback(for key: String) -> String? {
        switch key {
        case "距离开场":
            switch selectedLanguageKind {
            case .english:
                return "Until show starts"
            case .traditionalChinese:
                return "距離開場"
            case .other:
                return nil
            }
        default:
            return nil
        }
    }

    /// Compact time-unit labels are generated by the system when an explicit
    /// resource key is unavailable. This keeps units correct for an in-app
    /// language override without duplicating formatting logic at call sites.
    private static func measurementUnitFallback(for key: String) -> String? {
        let unit: Unit
        switch key {
        case "小时": unit = UnitDuration.hours
        case "分钟": unit = UnitDuration.minutes
        case "秒": unit = UnitDuration.seconds
        default: return nil
        }

        let formatter = MeasurementFormatter()
        formatter.locale = selectedLocale
        formatter.unitStyle = .long
        return formatter.string(from: unit)
    }

    private enum LanguageKind {
        case english
        case traditionalChinese
        case other
    }

    private static var selectedLanguageKind: LanguageKind {
        let identifier = selectedLocale.identifier
            .replacingOccurrences(of: "_", with: "-")
            .lowercased()
        if identifier.hasPrefix("en") {
            return .english
        }
        if identifier.hasPrefix("zh-hant")
            || identifier.hasPrefix("zh-tw")
            || identifier.hasPrefix("zh-hk")
            || identifier.hasPrefix("zh-mo") {
            return .traditionalChinese
        }
        return .other
    }

    /// AppLanguageManager persists the app override under this key. Reading it
    /// here keeps the shared localization seam independent from the app target,
    /// while still making an in-app language change affect generated labels.
    private static var selectedLocale: Locale {
        if let identifier = UserDefaults.standard.string(forKey: "appLanguage"), !identifier.isEmpty {
            return Locale(identifier: identifier)
        }
        return .autoupdatingCurrent
    }
}
