name: Cloudbase Functions

on:
  pull_request:
    paths:
      - "apps/cloudbase-functions/**"
      - ".github/workflows/cloudbase-functions.yml"
  push:
    branches:
      - main
    paths:
      - "apps/cloudbase-functions/**"
      - ".github/workflows/cloudbase-functions.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/cloudbase-functions

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm test
